

# This environment is intended to for testing purpose
resources:
  - ../base/quickfood
  - ../base/alloy

# To use a custom image (e.g., locally built), uncomment `newName` and `newTag` below.
# Example: docker build -t local-quickfood:latest . && minikube image load local-quickfood:latest
images:
  - name: ghcr.io/grafana/quickfood-local
    # newName: local-quickfood
    # newTag: latest
# Note: Do not commit changes to newName/newTag values (leave commented). TODO: consider Kustomize's env var substitution 

# For telemetry functionality, change the following lines to match your configuration.
secretGenerator:
  - name: grafana-alloy-credentials
    envs:
    - .env

# You can use the following generator to add additional environment variables to all QuickFood pods.
configMapGenerator:
  - name: quickfood-env
    envs:
    # load FARO variables
    - .env
    literals:
      # Enable tracing
      - QUICKFOOD_OTLP_ENDPOINT=http://grafana-alloy:4318
  - name: alloy-config
    files:
      - ./config/config.alloy
