# service.name: 'config'
# service.component: 'config' (defined in app code)
apiVersion: apps/v1
kind: Deployment
metadata:
  # unique name for this deployment resource
  name: quickfood-config
  labels: &configLabels # application name: groups all related resources
    app.k8s.io/name: quickfood
    # component type: defines the role of this deployment
    app.kubernetes.io/component: service
    # instance id: used for service discovery and telemetry (service.name/service_name attrs)
    app.kubernetes.io/instance: config
spec:
  replicas: 1
  selector:
    matchLabels: *configLabels
  template:
    metadata:
      labels: *configLabels
    spec:
      containers:
        - name: quickfood
          image: ghcr.io/grafana/quickfood-local:0.15.21
          ports:
            - name: http
              containerPort: 3333
          envFrom:
            - configMapRef:
                name: quickfood-env-common
            - configMapRef:
                name: quickfood-env
                optional: true
          env:
            - name: QUICKFOOD_ENABLE_CONFIG_SERVICE
              value: "1"
            - name: QUICKFOOD_OTEL_SERVICE_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUICKFOOD_OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/instance']
---
# Configures value for QUICKFOOD_CONFIG_ENDPOINT (set in kustomization.yaml)
apiVersion: v1
kind: Service
metadata:
  name: quickfood-config
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: config
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
